# -*- coding: utf-8 -*-
"""Estética: Planejamento e Engajamento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CroifPqc0xc0njjtg_5rWit45LkxokZo
"""

import pandas as pd
from datetime import datetime, timedelta


start_date = datetime.now()


calendar = []


for i in range(30):
    date = start_date + timedelta(days=i)

    calendar.append({
        'Data': date.strftime('%Y-%m-%d'),
        'Postagem': f'Dia {i+1}: {i % 5 + 1} - {["Dicas de beleza", "Antes e depois", "Tutorial", "Destaque de produtos", "Post interativo"][i % 5]}',
        'Stories': f'Dia {i+1}: {["Bastidores", "Enquete", "FAQ", "Promoção", "Testemunho"][i % 5]}'
    })


content_calendar = pd.DataFrame(calendar)


content_calendar